version: "3.8"
services:
  backend:
    build: C:\Users\IGNITER\Documents\GITHUB\EcoTips\Back_end\Ecotips_Back_End\demo
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build: C:\Users\IGNITER\Documents\GITHUB\EcoTips\Front_web\front_web
    ports:
      - "5173:5173" 
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_db
    ports:
      - "3306:3306"
